---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kcm
  namespace: kcm-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/k0rdent/kcm/charts/kcm
  ref:
    tag: 0.0.7
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kcm
  namespace: kcm-system
spec:
  chartRef:
    kind: OCIRepository
    name: kcm
    namespace: kcm-system
  interval: 10m
  values:
    cert-manager:
      enabled: true
    controller:
      createAccessManagement: true
      createManagement: true
    flux2:
      enabled: false

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kcm-controller-interaction
  namespace: flux-system
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/instance: kcm-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: kcm
    ports:
    - port: http
  podSelector:
    matchLabels:
      app: source-controller
  policyTypes:
  - Ingress
  
